apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: delery1/fscc-discovery-service:s4
          ports:
            - containerPort: 8761
          env:
            - name: SERVER_PORT
              value: "8761"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "discovery-service"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "false"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE
              value: http://discovery-service:8761/eureka/
            - name: EUREKA_SERVER_ENABLE_SELF_PRESERVATION
              value: "false"
            - name: EUREKA_SERVER_EVICTION_INTERVAL_TIMER_IN_MS
              value: "30000"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  selector:
    app: discovery-service
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: NodePort
