server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: login-service
          uri: ${LOGIN_URI:http://login-service:8083}  # Change localhost to the actual host if needed
          predicates:
            - Path=/api/auth/**
          filters:
            - AuthenticationFilter

        - id: registration-service
          uri: ${REGISTRATION_URI:http://registration-service:8082}  # Change localhost to the actual host if needed
          predicates:
            - Path=/api/registration/**
          filters:
            - AuthenticationFilter

        - id: employee-service
          uri: ${EMPLOYEE_URI:http://employee-service:8081}  # Change localhost to the actual host if needed
          predicates:
            - Path=/api/employee/**
          filters:
            - AuthenticationFilter
# Discovery
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://discovery-service:8761/eureka/}

#  application:
#    name: api-gateway

#JWT
app:
  jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb


#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://discovery-service:8761/eureka/

#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT-ZONE:http://localhost:8761/eureka}










#spring:
#  application:
#    name: api-gateway
#
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#
#  #Discoery
#  eureka:
#    client:
#      service-url:
#        defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http//localhost:8761/eureka}



# Eureka Client Service Name
#spring.application.name= api-gateway
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#server.port=8084

# This allows API-Gateway to search for services on Eureka Server
#spring.cloud.gateway.discovery.locator.enabled=true






#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: LOGIN-SERVICE
#          uri: lb://LOGIN-SERVICE
#          predicates:
#            - Path=/api/auth/**
#          filters:
#            - AuthenticationFilter
#
#
#        - id: REGISTRATION-SERVICE
#          uri: lb://REGISTRATION-SERVICE
#          predicates:
#            - Path=/api/registration/**
#          filters:
#            - AuthenticationFilter
#
#        - id: EMPLOYEE-SERVICE
#          uri: lb://EMPLOYEE-SERVICE
#          predicates:
#            - Path=/api/employee/**
#          filters:
#            - AuthenticationFilter
