apiVersion: v1
kind: Service
metadata:
  name: angular-ui
spec:
  selector:
    app: angular-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4200
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-ui
  template:
    metadata:
      labels:
        app: angular-ui
    spec:
      containers:
        - name: angular-ui
          image: delery1/fscc-angular-ui
          ports:
            - containerPort: 4200
          volumeMounts:
            - name: proxy-config-volume
              mountPath: /app/proxy.conf.json
              subPath: proxy.conf.json
      volumes:
        - name: proxy-config-volume
          configMap:
            name: proxy-config
