# loginservice-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loginservice
  template:
    metadata:
      labels:
        app: loginservice
    spec:
      containers:
        - name: loginservice
          image: delery1/fscc-login-service:s4
          ports:
            - containerPort: 8083
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://10.4.1.16:8761/eureka/
            - name: EUREKA_CLIENT_REGISTER-WITH-EUREKA
              value: "true"
            - name: EUREKA_CLIENT_PREFER-IP-ADDRESS
              value: "true"
            - name: EUREKA_CLIENT_FETCH-REGISTRY
              value: "true"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: login-service
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysqldblogin-service:3306/logindb
            - name: SPRING_DATASOURCE_USERNAME
              value: delery
            - name: SPRING_DATASOURCE_PASSWORD
              value: delery
            - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
              value: com.mysql.cj.jdbc.Driver
            - name: SPRING_JPA_HIBERNATE_DDL-AUTO
              value: update
            - name: SPRING_JPA_SHOW-SQL
              value: "true"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: org.hibernate.dialect.MySQLDialect
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: jwt-secret-config
                  key: JWT_SECRET
---
# Service for loginservice
apiVersion: v1
kind: Service
metadata:
  name: loginservice-service
spec:
  selector:
    app: loginservice
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP  # Change to ClusterIP

---
# Deployment for mysqldblogin
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldblogin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldblogin
  template:
    metadata:
      labels:
        app: mysqldblogin
    spec:
      containers:
        - name: mysqldblogin
          image: mysql:5.7  # Specify a MySQL version
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: logindb
            - name: MYSQL_USER
              value: delery
            - name: MYSQL_PASSWORD
              value: delery
            - name: MYSQL_ROOT_PASSWORD
              value: delery
      restartPolicy: Always
      # Add volume mounts, resources, etc. if needed

---
# Service for mysqldblogin
apiVersion: v1
kind: Service
metadata:
  name: mysqldblogin-service
spec:
  selector:
    app: mysqldblogin
  ports:
    - protocol: TCP
      port: 3306  # Use the same port as MySQL container
      targetPort: 3306
  type: ClusterIP  # Change to ClusterIP
